# Default values for spring-boot-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
